module.exports.BaseFieldsModel = require('./BaseFields.model');
module.exports.UserModel = require('./User.model');
module.exports.UserAgentModel = require('./UserAgent.model');
module.exports.RoleModel = require('./Role.model');
module.exports.NotificationModel = require('./Notification.model'); // Keep Notification for now as it might be used by system
module.exports.AttachmentsModel = require('./Attachments.model');
module.exports.OrganizationModel = require('./Organization.model');
module.exports.GroupModel = require('./Group.model');
module.exports.TicketModel = require('./Ticket.model');
module.exports.TicketCommentModel = require('./TicketComment.model');
module.exports.SlaPolicyModel = require('./SlaPolicy.model');
